# Generated by Django 5.2.7 on 2025-11-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Main article content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the article was created'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this article has been approved by an editor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='journalist',
            field=models.ForeignKey(help_text='The user who wrote this article', limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Optional publisher this article is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Article headline', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the article was last modified'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(help_text='Newsletter body content'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this newsletter was created'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='journalist',
            field=models.ForeignKey(help_text='The journalist who wrote this newsletter', limit_choices_to={'role': 'JOURNALIST'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(help_text='Newsletter subject/headline', max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(help_text='Editors who can approve content for this publisher', limit_choices_to={'role': 'EDITOR'}, related_name='publisher_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(help_text='Journalists who can write for this publisher', limit_choices_to={'role': 'JOURNALIST'}, related_name='publisher_journalists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text="The publisher's display name", max_length=200),
        ),
    ]
